CREATE TABLE alunos_coleta (
  id int NOT NULL,
  pressao_minima int DEFAULT NULL,
  pressao_maxima int DEFAULT NULL,
  pressao varchar (25) DEFAULT NULL,
  dextro_mgl int DEFAULT NULL,
  dextro varchar(10) DEFAULT NULL,
  peso_kg float DEFAULT NULL,
  estatura_metros float DEFAULT NULL,
  imc float DEFAULT NULL,
  resultado_imc varchar(25) DEFAULT NULL,
  circ_abdominal_cm int DEFAULT NULL,
  resultado_circ_abd varchar(25) DEFAULT NULL,
  oculos tinyint DEFAULT NULL,
  acuidade_visual_direita float DEFAULT NULL,
  acuidade_visual_esquerda float DEFAULT NULL,
  bioimpedancia_de_gordura float DEFAULT NULL,
  bioimpedancia_massa_magra_kg float DEFAULT NULL,
  bioimpedancia_massa_gorda_kg float DEFAULT NULL,
  hipertensao tinyint DEFAULT NULL,
  diabetes tinyint DEFAULT NULL,
  convulsoes tinyint DEFAULT NULL,
  alergias tinyint DEFAULT NULL,
  qual_alergia varchar(45) DEFAULT NULL,
  doenca_cronica_tratamento tinyint DEFAULT NULL,
  qual_doenca_cronica_tratamento varchar(45) DEFAULT NULL,
  medicamento_continuo tinyint DEFAULT NULL,
  qual_medicamento_continuo varchar(45) DEFAULT NULL,
  renda_pessoas_casa varchar(65) DEFAULT NULL,
  qtd_pessoas_casa tinyint DEFAULT NULL,
  trabalha tinyint DEFAULT NULL,
  cargo varchar(45) DEFAULT NULL,
  trabalho_hrs_dia tinyint DEFAULT NULL,
  fuma tinyint DEFAULT NULL,
  atividade_fisica tinyint DEFAULT NULL,
  qual_atividade_fisica varchar(65) DEFAULT NULL,
  qtas_vzs_semana_atividade_fisica tinyint DEFAULT NULL,
  qtas_hrs_atividade_fisica varchar(20) DEFAULT NULL,
  qtas_hrs_dorme varchar(25) DEFAULT NULL,
  historico_doencas tinyint DEFAULT NULL,
  cancer tinyint DEFAULT NULL,
  diabates tinyint DEFAULT NULL,
  doencas_cardiovasculares tinyint DEFAULT NULL,
  alzheimer tinyint DEFAULT NULL,
  asma tinyint DEFAULT NULL,
  colesterol_alto tinyint DEFAULT NULL,
  pressao_alta tinyint DEFAULT NULL,
  disturbios_psiquiatricos tinyint DEFAULT NULL,
  doencas_raras tinyint DEFAULT NULL,
  outros varchar(45) DEFAULT NULL,
  qtos_copos_agua varchar(20) DEFAULT NULL,
  agua tinyint DEFAULT NULL,
  dieta tinyint DEFAULT NULL,
  suplementacao_alimentar_uili tinyint DEFAULT NULL,
  orientacao_nutricional tinyint DEFAULT NULL,
  qtas_refeicoes_dia varchar(10) DEFAULT NULL,
  qtas_refeicoes_em_casa varchar(10) DEFAULT NULL,
  qtas_refeicoes_fora varchar(10) DEFAULT NULL,
  prepara_propria_refeicao tinyint DEFAULT NULL,
  mae_pai_prepara_refeicao varchar(10) DEFAULT NULL,
  tios_avos_prepara_refeicao varchar(10) DEFAULT NULL,
  irmaos_prepara_refeicao varchar(10) DEFAULT NULL,
  empregada_prepara_refeicao varchar(10) DEFAULT NULL,
  outrosi_prepara_refeicao varchar(10) DEFAULT NULL,
  adiciona_sal_dps_pronto tinyint DEFAULT NULL,
  adiciona_acucar_liquidos tinyint DEFAULT NULL,
  restricao_alimento_ovos tinyint DEFAULT NULL,
  restricao_alimento_farinha_trigo tinyint DEFAULT NULL,
  restricao_alimento_leite_derivados tinyint DEFAULT NULL,
  restricao_alimento_soja tinyint DEFAULT NULL,
  restricao_alimento_frutos_mar_peixe tinyint DEFAULT NULL,
  restricao_alimento_nenhum tinyint DEFAULT NULL,
  restricao_alimento_outros tinyint DEFAULT NULL,
  porcao_maior_menor_grupo_alimento varchar(30) DEFAULT NULL,
  res_porcao_leite CHAR(3),
  porcao_maior_menor_grupo_alimento_leite varchar(30) DEFAULT NULL,
  res_porcao_carne CHAR(3),
  porcao_maior_menor_grupo_alimento_carne varchar(30) DEFAULT NULL,
  res_porcao_oleo CHAR(3),
  porcao_maior_menor_grupo_alimento_oleo varchar(30) DEFAULT NULL,
  res_porcao_petisco CHAR(3),
  porcao_maior_menor_grupo_alimento_petisco varchar(30) DEFAULT NULL,
  res_porcao_cereal CHAR(3),
  porcao_maior_menor_grupo_alimento_cereal varchar(30) DEFAULT NULL,
  res_porcao_legume CHAR(3),
  porcao_maior_menor_grupo_alimento_legume varchar(30) DEFAULT NULL,
  res_porcao_hortalica CHAR(3),
  porcao_maior_menor_grupo_alimento_hortalica varchar(30) DEFAULT NULL,
  res_porcao_sobremesa CHAR(3),
  porcao_maior_menor_grupo_alimento_sobremesa varchar(30) DEFAULT NULL,
  res_porcao_bebida CHAR(3),
  porcao_maior_menor_grupo_alimento_bebida varchar(30) DEFAULT NULL,
  res_porcao_dieta CHAR(3),
  PRIMARY KEY (id),
  FOREIGN KEY (id) REFERENCES alunos (id)
)